// Code generated by "stringer -type configError -output config_error_string.go -linecomment"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errConfigUnused-1]
}

const _configError_name = "errConfigUnused"

var _configError_index = [...]uint8{0, 15}

func (i configError) String() string {
	i -= 1
	if i < 0 || i >= configError(len(_configError_index)-1) {
		return "configError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _configError_name[_configError_index[i]:_configError_index[i+1]]
}
