// Code generated by "stringer -linecomment -type parseError -output parse_error_string.go"; DO NOT EDIT.

package optstr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errBadUtf8Encoding-1]
	_ = x[errExpectKey-2]
	_ = x[errBadKey-3]
	_ = x[errBadRawValue-4]
	_ = x[errExpectValue-5]
	_ = x[errExpectEQ-6]
}

const _parseError_name = "bad utf-8 encodingexpect keybad keybad raw valueexpect valueexpect '='"

var _parseError_index = [...]uint8{0, 18, 28, 35, 48, 60, 70}

func (i parseError) String() string {
	i -= 1
	if i < 0 || i >= parseError(len(_parseError_index)-1) {
		return "parseError(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _parseError_name[_parseError_index[i]:_parseError_index[i+1]]
}
